### ISSUE TITLE
Unresolved reference source /sink

### ISSUE THREAD

**Issue by enigmablue** [flyerhq/react-native-android-uri-path#12]
Hi i got these two when trying to run. Any idea?

flyer/rnandroiduripath/RNAndroidURIPathModule.kt: (33, 37): Unresolved reference: source
flyer/rnandroiduripath/RNAndroidURIPathModule.kt: (34, 33): Unresolved reference: sink

My RN is   "react-native": "0.63.3",
  "@flyerhq/react-native-android-uri-path": "^2.2.0",

**Comment by enigmablue** [comment]
Error went away when i downgraded to v1

**Comment by dellwatson** [comment]
same issue on react-native 0.63.4, I re-install to library version 1.0.3 and it able to build android again

**Comment by demchenkoalex** [comment]
Hey, `v2.1.3` is fine, see release notes for `v2.2.0`, there was a migration to React Native 0.65, where old methods were removed. Because they were deprecated for a while I thought this change will be backwards compatible, but apparently not. So if you'll have React Native 0.65 use latest, if not, previous build `v2.1.3` is fine. There is no change in logic, just new APIs are used.

**Comment by ElangoPrince** [comment]
@dellwatson I'm using **"2.1.3"** And 
**"react": "17.0.1",**
**"react-native": "0.64.2",**
Still I'm getting build failed with 
```
> Task :flyerhq_react-native-android-uri-path:compileDebugKotlin FAILED
e: /Users/.../.../oyeti/node_modules/@flyerhq/react-native-android-uri-path/android/src/main/java/chat/flyer/rnandroiduripath/RNAndroidURIPathModule.kt: (33, 37): Unresolved reference: source
e: /Users/.../.../oyeti/node_modules/@flyerhq/react-native-android-uri-path/android/src/main/java/chat/flyer/rnandroiduripath/RNAndroidURIPathModule.kt: (34, 33): Unresolved reference: sink

```
