### ISSUE TITLE
Handling API 29 Content:// msf prefix real paths

### ISSUE THREAD

**Issue by enigmablue** [flyerhq/react-native-android-uri-path#13]
I'm trying to use this library because was hoping it could help me get the real path (only API 29, and on Pixel 3a) to this content://
`content://com.android.providers.downloads.documents/document/msf:12`

Related to these: 

- https://stackoverflow.com/questions/60861522/how-to-get-path-from-given-uri-in-android
- https://github.com/Javernaut/WhatTheCodec/issues/2- 

Unfortunately, its still getting "Permission Denial: reading com.android.providers.downloads.DownloadStorageProvider uri content://com.android.providers.downloads.documents/document/msf:12 from pid=21777, uid=10103 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs"

Any idea?

**Comment by demchenkoalex** [comment]
Hey @enigmablue unfortunately I have 0 experience in Android and this solution I have here I have found on some forums, after googling for days. Since then, this solution worked in production, for different devices, when selecting files usually using `react-native-document-picker`. In your case, from what I understood, Android somehow differently manages some specific files or something downloaded (?) so this will require help of a native Android developer. I have a Xiaomi device with Android 10 (API 29) so if you can provide step by step what I need to do to see this, that would be a start. I can try some code you posted above, but if that won't work I will leave this issue as "help wanted".

**Comment by enigmablue** [comment]
Hey! i managed to solve this as of yesterday. It turns out that the problem was because i should not pass in a decoded URI when trying to resolve the content:// (therefore when trying to do a msf:12, per the example above, it fails). Passing an un-decoded URI into this package is perfect and it resolves nicely. 

However, doing a decodeURIComponent afterwards on the post-resolved path is necessary for rnfs uploading because somehow that requires a decoded component.

**Comment by demchenkoalex** [comment]
Thanks for letting me know!
